export const categories = {
  arxiv: [
    { value: 'cs.AI', label: 'Artificial Intelligence' },
    { value: 'cs.AR', label: 'Hardware Architecture' },
    { value: 'cs.CC', label: 'Computational Complexity' },
    { value: 'cs.CE', label: 'Computational Engineering, Finance, and Science' },
    { value: 'cs.CG', label: 'Computational Geometry' },
    { value: 'cs.CL', label: 'Computation and Language' },
    { value: 'cs.CR', label: 'Cryptography and Security' },
    { value: 'cs.CV', label: 'Computer Vision and Pattern Recognition' },
    { value: 'cs.CY', label: 'Computers and Society' },
    { value: 'cs.DB', label: 'Databases' },
    { value: 'cs.DC', label: 'Distributed, Parallel, and Cluster Computing' },
    { value: 'cs.DL', label: 'Digital Libraries' },
    { value: 'cs.DM', label: 'Discrete Mathematics' },
    { value: 'cs.DS', label: 'Data Structures and Algorithms' },
    { value: 'cs.ET', label: 'Emerging Technologies' },
    { value: 'cs.FL', label: 'Formal Languages and Automata Theory' },
    { value: 'cs.GL', label: 'General Literature' },
    { value: 'cs.GR', label: 'Graphics' },
    { value: 'cs.GT', label: 'Computer Science and Game Theory' },
    { value: 'cs.HC', label: 'Human-Computer Interaction' },
    { value: 'cs.IR', label: 'Information Retrieval' },
    { value: 'cs.IT', label: 'Information Theory' },
    { value: 'cs.LG', label: 'Machine Learning' },
    { value: 'cs.LO', label: 'Logic in Computer Science' },
    { value: 'cs.MA', label: 'Multiagent Systems' },
    { value: 'cs.MM', label: 'Multimedia' },
    { value: 'cs.MS', label: 'Mathematical Software' },
    { value: 'cs.NA', label: 'Numerical Analysis' },
    { value: 'cs.NE', label: 'Neural and Evolutionary Computing' },
    { value: 'cs.NI', label: 'Networking and Internet Architecture' },
    { value: 'cs.OH', label: 'Other Computer Science' },
    { value: 'cs.OS', label: 'Operating Systems' },
    { value: 'cs.PF', label: 'Performance' },
    { value: 'cs.PL', label: 'Programming Languages' },
    { value: 'cs.RO', label: 'Robotics' },
    { value: 'cs.SC', label: 'Symbolic Computation' },
    { value: 'cs.SD', label: 'Sound' },
    { value: 'cs.SE', label: 'Software Engineering' },
    { value: 'cs.SI', label: 'Social and Information Networks' },
    { value: 'cs.SY', label: 'Systems and Control' },
  ],
  reddit: [
    { value: 'r/microsaas', label: 'r/microsaas' },
    { value: 'r/indiehackers', label: 'r/indiehackers' },
    { value: 'r/sideproject', label: 'r/sideproject' },
  ],
  product_hunt: [
    { value: 'Web Design', label: 'Web Design' },
    { value: 'Inclusivity', label: 'Inclusivity' },
    { value: 'Education', label: 'Education' },
    { value: 'Calendar', label: 'Calendar' },
    { value: 'Remote Work', label: 'Remote Work' },
    { value: 'API', label: 'API' },
    { value: 'Data Visualization', label: 'Data Visualization' },
    { value: 'Audio', label: 'Audio' },
    { value: 'Meetings', label: 'Meetings' },
    { value: 'Events', label: 'Events' },
    { value: 'Medical', label: 'Medical' },
    { value: 'Customer Communication', label: 'Customer Communication' },
    { value: 'Business Travel', label: 'Business Travel' },
    { value: 'Messaging', label: 'Messaging' },
    { value: 'Customer Success', label: 'Customer Success' },
    { value: 'Marketing', label: 'Marketing' },
    { value: 'Growth Hacking', label: 'Growth Hacking' },
    { value: 'Operations', label: 'Operations' },
    { value: 'SaaS', label: 'SaaS' },
    { value: 'Maker Tools', label: 'Maker Tools' },
    { value: 'Security', label: 'Security' },
    { value: 'Database', label: 'Database' },
    { value: 'Online Learning', label: 'Online Learning' },
    { value: 'Movies', label: 'Movies' },
    { value: 'Social media marketing', label: 'Social media marketing' },
    { value: 'Dogs', label: 'Dogs' },
    { value: 'Email', label: 'Email' },
    { value: 'Mac', label: 'Mac' },
    { value: 'Family', label: 'Family' },
    { value: 'Privacy', label: 'Privacy' },
    { value: 'Venture Capital', label: 'Venture Capital' },
    { value: 'Video Art', label: 'Video Art' },
    { value: 'WordPress', label: 'WordPress' },
    { value: 'Text Editors', label: 'Text Editors' },
    { value: 'Email Marketing', label: 'Email Marketing' },
    { value: 'User Experience', label: 'User Experience' },
    { value: 'Design', label: 'Design' },
    { value: 'Task Management', label: 'Task Management' },
    { value: 'Investing', label: 'Investing' },
    { value: 'E-Commerce', label: 'E-Commerce' },
    { value: 'Lifestyle', label: 'Lifestyle' },
    { value: 'Human Resources', label: 'Human Resources' },
    { value: 'LinkedIn', label: 'LinkedIn' },
    { value: 'Animation', label: 'Animation' },
    { value: 'Digital Art', label: 'Digital Art' },
    { value: 'Notion', label: 'Notion' },
    { value: 'Artificial Intelligence', label: 'Artificial Intelligence' },
    { value: 'Travel', label: 'Travel' },
    { value: 'Health', label: 'Health' },
    { value: 'Data', label: 'Data' },
    { value: 'Bots', label: 'Bots' },
    { value: 'Writing', label: 'Writing' },
    { value: 'YouTube', label: 'YouTube' },
    { value: 'GitHub', label: 'GitHub' },
    { value: 'SEO', label: 'SEO' },
    { value: 'Tech', label: 'Tech' },
    { value: 'Productivity', label: 'Productivity' },
    { value: 'Development', label: 'Development' },
    { value: 'SDK', label: 'SDK' },
    { value: 'Community', label: 'Community' },
    { value: 'Android', label: 'Android' },
    { value: 'Social Networking', label: 'Social Networking' },
    { value: 'Music', label: 'Music' },
    { value: 'Chrome Extensions', label: 'Chrome Extensions' },
    { value: 'Search', label: 'Search' },
    { value: 'Data & Analytics', label: 'Data & Analytics' },
    { value: 'CRM', label: 'CRM' },
    { value: 'Website Builder', label: 'Website Builder' },
    { value: 'Virtual Assistants', label: 'Virtual Assistants' },
    { value: 'Video', label: 'Video' },
    { value: 'Fundraising', label: 'Fundraising' },
    { value: 'Social Media', label: 'Social Media' },
    { value: 'Games', label: 'Games' },
    { value: 'Quantified Self', label: 'Quantified Self' },
    { value: 'Software Engineering', label: 'Software Engineering' },
    { value: 'Analytics', label: 'Analytics' },
    { value: 'Credit card', label: 'Credit card' },
    { value: 'Photography', label: 'Photography' },
    { value: 'Marketing automation', label: 'Marketing automation' },
    { value: 'Spreadsheets', label: 'Spreadsheets' },
    { value: 'Photo & Video', label: 'Photo & Video' },
    { value: 'Languages', label: 'Languages' },
    { value: 'Notes', label: 'Notes' },
    { value: 'iOS', label: 'iOS' },
    { value: 'News', label: 'News' },
    { value: 'Web App', label: 'Web App' },
    { value: 'Data Science', label: 'Data Science' },
    { value: 'Hiring', label: 'Hiring' },
    { value: 'FemTech', label: 'FemTech' },
    { value: 'Fintech', label: 'Fintech' },
    { value: 'Monetization', label: 'Monetization' },
    { value: 'Advertising', label: 'Advertising' },
    { value: 'eBook Reader', label: 'eBook Reader' },
    { value: 'Design Tools', label: 'Design Tools' },
    { value: 'Video Streaming', label: 'Video Streaming' },
    { value: 'Affiliate marketing', label: 'Affiliate marketing' },
    { value: 'Apple', label: 'Apple' },
    { value: 'Business', label: 'Business' },
    { value: 'Art', label: 'Art' },
    { value: 'Developer Tools', label: 'Developer Tools' },
    { value: 'Sales', label: 'Sales' },
    { value: 'Books', label: 'Books' },
    { value: 'Career', label: 'Career' },
    { value: 'Open Source', label: 'Open Source' },
    { value: 'Business Intelligence', label: 'Business Intelligence' },
    { value: 'A/B Testing', label: 'A/B Testing' },
    { value: 'No-Code', label: 'No-Code' },
    { value: 'Health & Fitness', label: 'Health & Fitness' },
  ],
} as const;

export type CategoryType = 'arxiv' | 'reddit' | 'product_hunt';
